import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
export function getSupabaseAdmin() { const url = Deno.env.get("SUPABASE_URL"); const key = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"); if (!url || !key) throw new Error("Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY"); return createClient(url, key); }
export async function startIngestionLog(supabase: ReturnType<typeof createClient>, platformAccountId: string, jobType: string): Promise<string> { const { data, error } = await supabase.from("ingestion_logs").insert({ platform_account_id: platformAccountId, job_type: jobType, status: "running", started_at: new Date().toISOString() }).select("id").single(); if (error) throw new Error(`Failed to create ingestion log: ${error.message}`); return data.id; }
export async function completeIngestionLog(supabase: ReturnType<typeof createClient>, logId: string, stats: any) { await supabase.from("ingestion_logs").update({ status: "success", completed_at: new Date().toISOString(), ...stats }).eq("id", logId); }
export async function failIngestionLog(supabase: ReturnType<typeof createClient>, logId: string, error: any) { await supabase.from("ingestion_logs").update({ status: "failed", completed_at: new Date().toISOString(), error_message: typeof error === "string" ? error : error.message }).eq("id", logId); }
export async function getActiveAccounts(supabase: ReturnType<typeof createClient>, platform: string) { const { data, error } = await supabase.from("platform_accounts").select("*").eq("platform", platform).eq("is_active", true); if (error) throw new Error(`Failed to fetch ${platform} accounts: ${error.message}`); return data || []; }
export async function fetchWithRetry(url: string, options: RequestInit = {}, maxRetries = 3, baseDelayMs = 1000): Promise<Response> { for (let attempt = 0; attempt <= maxRetries; attempt++) { try { const r = await fetch(url, options); if (r.status === 429 || r.status >= 500) { if (attempt < maxRetries) { await new Promise(res => setTimeout(res, baseDelayMs * Math.pow(2, attempt))); continue; } } return r; } catch (e) { if (attempt < maxRetries) { await new Promise(res => setTimeout(res, baseDelayMs * Math.pow(2, attempt))); continue; } throw e; } } throw new Error(`Failed after ${maxRetries} retries: ${url}`); }
export function jsonResponse(data: unknown, status = 200) { return new Response(JSON.stringify(data), { status, headers: { "Content-Type": "application/json" } }); }
export function errorResponse(message: string, status = 500) { return new Response(JSON.stringify({ error: message }), { status, headers: { "Content-Type": "application/json" } }); }
