import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { DragDropContext } from '@hello-pangea/dnd';
import NewsletterCanvas from './NewsletterCanvas';
import BlockToolbox from './BlockToolbox';
import SubscribeConfig from './SubscribeConfig';
import {
  SCHEDULE_PRESETS,
  DEFAULT_REPORT_CONFIG,
  slugify,
  createBlock,
} from './reportBuilderConstants';

// Derive section_ids from canvas blocks for backward compat
function sectionIdsFromCanvas(canvas) {
  return (canvas || [])
    .filter(b => b.type === 'section' && b.sectionId)
    .map(b => b.sectionId);
}

// Auto-migrate old section_ids-only config → canvas blocks
function migrateToCanvas(config) {
  if (config?.canvas && config.canvas.length > 0) return config.canvas;
  const ids = config?.section_ids || [];
  if (ids.length === 0) return [];
  return ids.map(id => createBlock('section', { sectionId: id }));
}

// ── Static block → inline HTML (mirrors run-report renderStaticBlock) ──

function escapeHtml(text) {
  return (text || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function renderBlockToHtml(block, sectionsById) {
  const s = block.style || {};
  switch (block.type) {
    case 'heading': {
      const tag = `h${block.level || 1}`;
      const style = `margin:0 0 8px;font-family:${s.fontFamily || 'DM Sans'},sans-serif;font-size:${s.fontSize || '24px'};font-weight:${s.fontWeight || '700'};color:${s.color || '#1a1a2e'};text-align:${s.textAlign || 'left'};line-height:1.3;`;
      return `<${tag} style="${style}">${block.content || ''}</${tag}>`;
    }
    case 'text': {
      const style = `font-family:${s.fontFamily || 'DM Sans'},sans-serif;font-size:${s.fontSize || '14px'};color:${s.color || '#333333'};text-align:${s.textAlign || 'left'};line-height:${s.lineHeight || '1.6'};`;
      return `<div style="${style}">${block.content || ''}</div>`;
    }
    case 'image': {
      if (!block.src) return '';
      const style = `width:${s.width || '100%'};border-radius:${s.borderRadius || '4px'};display:block;`;
      return `<img src="${escapeHtml(block.src)}" alt="${escapeHtml(block.alt || '')}" style="${style}" />`;
    }
    case 'divider':
      return `<hr style="border:none;border-top:${s.borderWidth || '1px'} solid ${s.borderColor || '#e2e8f0'};margin:${s.margin || '8px 0'};" />`;
    case 'spacer':
      return `<div style="height:${s.height || '24px'};"></div>`;
    case 'columns': {
      const cols = block.columns || [];
      const colHtml = cols.map(col => {
        const inner = (col.blocks || []).map(b => renderBlockToHtml(b, sectionsById)).join('');
        return `<td style="width:${Math.floor(100 / cols.length)}%;vertical-align:top;padding:0 8px;">${inner}</td>`;
      }).join('');
      return `<table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;"><tr>${colHtml}</tr></table>`;
    }
    case 'section': {
      const section = sectionsById?.get(block.sectionId);
      const name = section?.name || 'Unknown Section';
      const kind = section?.kind || 'custom';
      return `<div style="margin:12px 0;padding:16px 20px;background:#f0f4ff;border:1px dashed #6366f1;border-radius:8px;">
        <div style="font-size:14px;font-weight:600;color:#4338ca;margin-bottom:4px;">${escapeHtml(name)}</div>
        <div style="font-size:11px;color:#6366f1;text-transform:uppercase;letter-spacing:0.05em;margin-bottom:4px;">${escapeHtml(kind)}</div>
        <div style="font-size:12px;color:#64748b;">This section is generated by AI at send time.</div>
      </div>`;
    }
    default:
      return '';
  }
}

function EmailPreview({ canvas, sectionsById, reportName }) {
  const today = new Date().toLocaleDateString('en-US', {
    weekday: 'long', month: 'long', day: 'numeric', year: 'numeric',
  });

  const contentHtml = (canvas || []).map(b => renderBlockToHtml(b, sectionsById)).join('\n');

  const fullHtml = `
    <div style="background:linear-gradient(135deg,#6366f1,#4f46e5);padding:24px 28px;border-radius:8px 8px 0 0;">
      <h1 style="margin:0;font-size:20px;font-weight:700;color:#ffffff;">${escapeHtml(reportName || 'Untitled Report')}</h1>
      <p style="margin:6px 0 0;font-size:13px;color:rgba(255,255,255,0.7);">${today}</p>
    </div>
    <div style="padding:24px 28px;font-size:14px;color:#334155;line-height:1.7;">
      ${contentHtml || '<p style="color:#94a3b8;text-align:center;padding:32px 0;">No blocks on canvas yet.</p>'}
    </div>
    <div style="text-align:center;padding:16px 0;font-size:11px;color:#94a3b8;border-top:1px solid #e2e8f0;">
      Powered by Mayday Studio
    </div>
  `;

  return (
    <div style={previewStyles.wrapper}>
      <div style={previewStyles.container}>
        <div
          style={previewStyles.emailCard}
          dangerouslySetInnerHTML={{ __html: fullHtml }}
        />
      </div>
    </div>
  );
}

const previewStyles = {
  wrapper: {
    flex: 1,
    overflowY: 'auto',
    background: '#f1f5f9',
    padding: '32px 24px',
  },
  container: {
    maxWidth: '640px',
    margin: '0 auto',
  },
  emailCard: {
    background: '#ffffff',
    borderRadius: '8px',
    border: '1px solid #e2e8f0',
    overflow: 'hidden',
    boxShadow: '0 2px 12px rgba(0,0,0,0.08)',
    fontFamily: "'DM Sans', 'Helvetica Neue', Arial, sans-serif",
  },
};

export default function ReportEditor({
  config,
  sections,
  saving,
  onSave,
  onCancel,
  onRunNow,
  running,
  onSectionCreated,
  onSectionDeleted,
}) {
  const isNew = !config?.id;
  const [draft, setDraft] = useState(() => ({
    ...DEFAULT_REPORT_CONFIG,
    ...config,
    section_ids: config?.section_ids || [],
    canvas: migrateToCanvas(config),
  }));
  const [errors, setErrors] = useState({});
  const [slugEdited, setSlugEdited] = useState(false);
  const [customCron, setCustomCron] = useState('');
  const [leftTab, setLeftTab] = useState('design'); // 'design' | 'settings' | 'preview'

  // Auto-generate slug from name
  useEffect(() => {
    if (!slugEdited && draft.name) {
      setDraft(d => ({ ...d, slug: slugify(d.name) }));
    }
  }, [draft.name, slugEdited]);

  // Init custom cron if schedule doesn't match a preset
  useEffect(() => {
    const isPreset = SCHEDULE_PRESETS.some(p => p.value === draft.schedule);
    if (draft.schedule && !isPreset) setCustomCron(draft.schedule);
  }, []); // eslint-disable-line

  const updateDraft = useCallback((updates) => {
    setDraft(d => ({ ...d, ...updates }));
    const cleared = {};
    for (const key of Object.keys(updates)) cleared[key] = undefined;
    setErrors(e => ({ ...e, ...cleared }));
  }, []);

  const handleSchedulePreset = useCallback((preset) => {
    if (preset.value === '__custom__') {
      updateDraft({ schedule: customCron || '' });
    } else {
      updateDraft({ schedule: preset.value });
    }
  }, [updateDraft, customCron]);

  const sectionsById = useMemo(() => {
    const map = new Map();
    for (const s of sections) map.set(s.id, s);
    return map;
  }, [sections]);

  // ── Canvas change handler (keeps section_ids in sync) ──────

  const handleCanvasChange = useCallback((newCanvas) => {
    const ids = sectionIdsFromCanvas(newCanvas);
    setDraft(d => ({ ...d, canvas: newCanvas, section_ids: ids }));
    setErrors(e => ({ ...e, canvas: undefined }));
  }, []);

  // Add a section as a canvas block
  const handleAddSection = useCallback((sectionId) => {
    // Prevent duplicates
    const exists = draft.canvas.some(b => b.type === 'section' && b.sectionId === sectionId);
    if (exists) return;
    const block = createBlock('section', { sectionId });
    const newCanvas = [...draft.canvas, block];
    handleCanvasChange(newCanvas);
  }, [draft.canvas, handleCanvasChange]);

  // Add a static block (from toolbox click)
  const handleAddBlock = useCallback((block) => {
    const newCanvas = [...draft.canvas, block];
    handleCanvasChange(newCanvas);
  }, [draft.canvas, handleCanvasChange]);

  const handleSectionCreated = useCallback((newSection) => {
    onSectionCreated?.(newSection);
    // Auto-add newly created section to canvas
    const block = createBlock('section', { sectionId: newSection.id });
    setDraft(d => {
      const newCanvas = [...(d.canvas || []), block];
      return { ...d, canvas: newCanvas, section_ids: sectionIdsFromCanvas(newCanvas) };
    });
  }, [onSectionCreated]);

  // ── DragDropContext onDragEnd ───────────────────────────────

  const handleDragEnd = useCallback((result) => {
    const { source, destination, draggableId } = result;
    if (!destination) return;

    // 1) Reorder within canvas
    if (source.droppableId === 'canvas' && destination.droppableId === 'canvas') {
      const next = [...draft.canvas];
      const [moved] = next.splice(source.index, 1);
      next.splice(destination.index, 0, moved);
      handleCanvasChange(next);
      return;
    }

    // 2) Drop from block-toolbox → canvas
    if (source.droppableId === 'block-toolbox' && destination.droppableId === 'canvas') {
      const blockType = draggableId.replace('toolbox-', '');
      const block = createBlock(blockType);
      const next = [...draft.canvas];
      next.splice(destination.index, 0, block);
      handleCanvasChange(next);
      return;
    }

    // 3) Drop from sections-library → canvas
    if (source.droppableId === 'sections-library' && destination.droppableId === 'canvas') {
      const sectionId = draggableId.replace('section-', '');
      // Prevent duplicates
      const exists = draft.canvas.some(b => b.type === 'section' && b.sectionId === sectionId);
      if (exists) return;
      const block = createBlock('section', { sectionId });
      const next = [...draft.canvas];
      next.splice(destination.index, 0, block);
      handleCanvasChange(next);
      return;
    }
  }, [draft.canvas, handleCanvasChange]);

  // ── Validation ─────────────────────────────────────────────

  const validate = useCallback(() => {
    const errs = {};
    if (!draft.name.trim()) errs.name = 'Name is required';
    if (!draft.slug.trim()) errs.slug = 'Slug is required';
    else if (!/^[a-z0-9-]+$/.test(draft.slug)) errs.slug = 'Slug must be lowercase letters, numbers, and hyphens';
    if (!draft.canvas || draft.canvas.length === 0) errs.canvas = 'Add at least one block to the canvas';
    setErrors(errs);
    return Object.keys(errs).length === 0;
  }, [draft]);

  const handleSave = useCallback(() => {
    if (!validate()) return;
    onSave({
      ...draft,
      section_ids: sectionIdsFromCanvas(draft.canvas),
      output_format: 'html',
      updated_at: new Date().toISOString(),
    });
  }, [draft, validate, onSave]);

  const activeSchedulePreset = SCHEDULE_PRESETS.find(p => p.value === draft.schedule);
  const isCustomSchedule = draft.schedule && !activeSchedulePreset;

  // Section IDs currently on canvas (for "in report" badges)
  const canvasSectionIds = useMemo(() => sectionIdsFromCanvas(draft.canvas), [draft.canvas]);

  return (
    <DragDropContext onDragEnd={handleDragEnd}>
      <div style={styles.editor}>
        <div style={styles.columns}>
          {/* Left: Design / Settings tabs */}
          <div style={styles.leftCol}>
            {/* Tab bar */}
            <div style={styles.leftTabs}>
              <button
                style={{ ...styles.leftTab, ...(leftTab === 'design' ? styles.leftTabActive : {}) }}
                onClick={() => setLeftTab('design')}
              >
                Design
              </button>
              <button
                style={{ ...styles.leftTab, ...(leftTab === 'preview' ? styles.leftTabActive : {}) }}
                onClick={() => setLeftTab('preview')}
              >
                Preview
              </button>
              <button
                style={{ ...styles.leftTab, ...(leftTab === 'settings' ? styles.leftTabActive : {}) }}
                onClick={() => setLeftTab('settings')}
              >
                Settings
              </button>
            </div>

            {/* Design tab → Newsletter Canvas */}
            {leftTab === 'design' && (
              <>
                {errors.canvas && <div style={styles.canvasError}>{errors.canvas}</div>}
                <NewsletterCanvas
                  canvas={draft.canvas}
                  sectionsById={sectionsById}
                  onChange={handleCanvasChange}
                />
              </>
            )}

            {/* Preview tab → Email preview */}
            {leftTab === 'preview' && (
              <EmailPreview canvas={draft.canvas} sectionsById={sectionsById} reportName={draft.name} />
            )}

            {/* Settings tab → Identity, Delivery, Schedule */}
            {leftTab === 'settings' && (
              <div style={styles.scrollArea}>
                {/* Identity */}
                <div style={styles.section}>
                  <div style={styles.sectionTitle}>Identity</div>
                  <label style={styles.fieldLabel}>Name</label>
                  <input
                    style={{ ...styles.input, ...(errors.name ? styles.inputError : {}) }}
                    value={draft.name}
                    onChange={e => updateDraft({ name: e.target.value })}
                    placeholder="Daily Pitching Report"
                  />
                  {errors.name && <div style={styles.errorText}>{errors.name}</div>}

                  <label style={styles.fieldLabel}>Description</label>
                  <textarea
                    style={styles.textarea}
                    value={draft.description || ''}
                    onChange={e => updateDraft({ description: e.target.value })}
                    placeholder="What this report covers..."
                    rows={2}
                  />

                  <label style={styles.fieldLabel}>Slug</label>
                  <input
                    style={{ ...styles.input, ...(errors.slug ? styles.inputError : {}) }}
                    value={draft.slug}
                    onChange={e => { setSlugEdited(true); updateDraft({ slug: e.target.value }); }}
                    placeholder="daily-pitching-report"
                  />
                  {errors.slug && <div style={styles.errorText}>{errors.slug}</div>}
                </div>

                {/* Delivery */}
                <div style={styles.section}>
                  <div style={styles.sectionTitle}>Delivery</div>
                  <div style={styles.row}>
                    <label style={styles.toggleRow}>
                      <input
                        type="checkbox"
                        checked={draft.delivery?.inbox !== false}
                        onChange={e => updateDraft({ delivery: { ...draft.delivery, inbox: e.target.checked } })}
                        style={styles.checkbox}
                      />
                      <span>Research Inbox</span>
                    </label>
                    <label style={styles.toggleRow}>
                      <input
                        type="checkbox"
                        checked={draft.delivery?.email === true}
                        onChange={e => updateDraft({ delivery: { ...draft.delivery, email: e.target.checked } })}
                        style={styles.checkbox}
                      />
                      <span>Email</span>
                    </label>
                  </div>
                  {draft.delivery?.email && (
                    <>
                      <div style={styles.hint}>Sends to all team members with email reports enabled + external subscribers.</div>
                      <div style={{ marginTop: '16px', paddingTop: '16px', borderTop: '1px solid rgba(255,255,255,0.04)' }}>
                        <div style={{ fontSize: '12px', fontWeight: 600, color: 'rgba(255,255,255,0.4)', marginBottom: '4px' }}>Subscribe Page Branding</div>
                        <SubscribeConfig draft={draft} onUpdate={updateDraft} />
                      </div>
                    </>
                  )}
                </div>

                {/* Schedule */}
                <div style={styles.section}>
                  <div style={styles.sectionTitle}>Schedule</div>
                  <div style={styles.scheduleGrid}>
                    {SCHEDULE_PRESETS.map(p => (
                      <button
                        key={p.label}
                        onClick={() => handleSchedulePreset(p)}
                        style={{
                          ...styles.scheduleBtn,
                          ...((p.value === draft.schedule || (p.value === '__custom__' && isCustomSchedule)) ? styles.scheduleBtnActive : {}),
                        }}
                      >{p.label}</button>
                    ))}
                  </div>
                  {(isCustomSchedule || activeSchedulePreset?.value === '__custom__') && (
                    <div style={{ marginTop: '8px' }}>
                      <input
                        style={styles.input}
                        value={isCustomSchedule ? draft.schedule : customCron}
                        onChange={e => {
                          setCustomCron(e.target.value);
                          updateDraft({ schedule: e.target.value });
                        }}
                        placeholder="0 15 * * *"
                      />
                      <div style={styles.hint}>Cron: minute hour day month weekday (UTC)</div>
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* Footer */}
            <div style={styles.footer}>
              <button onClick={onCancel} style={styles.cancelBtn}>Cancel</button>
              <button
                onClick={onRunNow}
                disabled={!config?.id || running}
                style={{ ...styles.runBtn, ...(!config?.id || running ? styles.runBtnDisabled : {}) }}
                title={!config?.id ? 'Save first' : 'Run now'}
              >{running ? 'Running...' : 'Run Now'}</button>
              <button
                onClick={handleSave}
                disabled={saving}
                style={{ ...styles.saveBtn, ...(saving ? { opacity: 0.5 } : {}) }}
              >
                {saving ? 'Saving...' : isNew ? 'Create Report' : 'Save Changes'}
              </button>
            </div>
          </div>

          {/* Right: Block toolbox + sections library */}
          <div style={styles.rightCol}>
            <BlockToolbox
              sections={sections}
              selectedSectionIds={canvasSectionIds}
              onAddSection={handleAddSection}
              onSectionCreated={handleSectionCreated}
              onSectionDeleted={onSectionDeleted}
              onAddBlock={handleAddBlock}
            />
          </div>
        </div>
      </div>
    </DragDropContext>
  );
}

const styles = {
  editor: { display: 'flex', flexDirection: 'column', flex: 1, overflow: 'hidden' },
  columns: { display: 'flex', flex: 1, overflow: 'hidden' },
  leftCol: { flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden', minWidth: 0 },
  rightCol: { width: '300px', minWidth: '260px', flexShrink: 0, display: 'flex', flexDirection: 'column' },
  leftTabs: { display: 'flex', borderBottom: '1px solid rgba(255,255,255,0.06)', flexShrink: 0 },
  leftTab: {
    background: 'none', border: 'none', borderBottom: '2px solid transparent',
    color: 'rgba(255,255,255,0.4)', fontSize: '13px', fontWeight: 600, fontFamily: 'inherit',
    padding: '10px 20px', cursor: 'pointer', transition: 'color 0.12s, border-color 0.12s',
  },
  leftTabActive: { color: '#a5b4fc', borderBottomColor: '#6366f1' },
  canvasError: { fontSize: '11px', color: '#ef4444', padding: '6px 24px 0', flexShrink: 0 },
  scrollArea: { flex: 1, overflowY: 'auto', padding: '16px 24px 24px' },
  section: { marginBottom: '24px' },
  sectionTitle: { fontSize: '13px', fontWeight: 700, color: '#e2e8f0', marginBottom: '12px', textTransform: 'uppercase', letterSpacing: '0.5px' },
  fieldLabel: { display: 'block', fontSize: '12px', fontWeight: 600, color: 'rgba(255,255,255,0.5)', marginBottom: '6px', marginTop: '12px' },
  input: { width: '100%', background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '6px', color: '#ffffff', fontSize: '13px', padding: '8px 12px', fontFamily: 'inherit', boxSizing: 'border-box' },
  inputError: { borderColor: 'rgba(239,68,68,0.5)' },
  textarea: { width: '100%', background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '6px', color: '#ffffff', fontSize: '13px', padding: '8px 12px', fontFamily: 'inherit', resize: 'vertical', boxSizing: 'border-box' },
  errorText: { fontSize: '11px', color: '#ef4444', marginTop: '4px', marginBottom: '4px' },
  hint: { fontSize: '11px', color: 'rgba(255,255,255,0.25)', marginTop: '6px' },
  row: { display: 'flex', gap: '16px', alignItems: 'center', flexWrap: 'wrap' },
  toggleRow: { display: 'flex', alignItems: 'center', gap: '8px', fontSize: '13px', color: 'rgba(255,255,255,0.7)', cursor: 'pointer' },
  checkbox: { accentColor: '#6366f1' },
  scheduleGrid: { display: 'flex', flexWrap: 'wrap', gap: '6px' },
  scheduleBtn: { background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '6px', color: 'rgba(255,255,255,0.5)', fontSize: '12px', fontWeight: 600, fontFamily: 'inherit', padding: '6px 14px', cursor: 'pointer', transition: 'background 0.12s, border-color 0.12s, color 0.12s' },
  scheduleBtnActive: { background: 'rgba(99,102,241,0.15)', borderColor: 'rgba(99,102,241,0.4)', color: '#a5b4fc' },
  footer: { display: 'flex', alignItems: 'center', gap: '8px', padding: '14px 24px', borderTop: '1px solid rgba(255,255,255,0.06)', flexShrink: 0, justifyContent: 'flex-end' },
  cancelBtn: { background: 'none', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '6px', color: 'rgba(255,255,255,0.5)', fontSize: '13px', fontFamily: 'inherit', padding: '8px 18px', cursor: 'pointer' },
  runBtn: { background: 'rgba(255,255,255,0.06)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '6px', color: 'rgba(255,255,255,0.7)', fontSize: '13px', fontFamily: 'inherit', padding: '8px 18px', cursor: 'pointer', transition: 'opacity 0.12s' },
  runBtnDisabled: { opacity: 0.35, cursor: 'not-allowed' },
  saveBtn: { background: '#6366f1', border: 'none', borderRadius: '6px', color: '#ffffff', fontSize: '13px', fontWeight: 600, fontFamily: 'inherit', padding: '8px 22px', cursor: 'pointer', transition: 'opacity 0.12s' },
};
