import React, { useState, useEffect, useCallback } from 'react';
import { supabase } from '../../supabaseClient';
import { useAuth } from '../../contexts/AuthContext';
import { rotateGuestToken, guestJoinLink } from '../../lib/harbor/session';
import useVisibilityRefresh from '../../hooks/useVisibilityRefresh';
import { colors, spacing, radii, fontSizes, fontWeights, fontFamily } from '../../lib/styleTokens';
import { pill, button, input, card, sectionHeader } from '../../lib/styleRecipes';

// Harbor app home (staff side) — replaces the coming-soon teaser at '/harbor'.
// Sessions list + create form + guest-link copy + open room. Reads/writes
// harbor_sessions directly under RLS (all-staff surface: is_harbor_staff).
// Guests never see this page — they enter via the public /harbor/join/<token>
// route served before the auth gate (HarborJoin.js).

const STATUS_TONES = { scheduled: 'info', live: 'success', ended: 'danger' };
const STATUS_LABELS = { scheduled: 'Scheduled', live: 'Live', ended: 'Ended' };

export default function HarborHome({ onOpenRoom, onBackToLauncher }) {
  const { profile } = useAuth();
  const [sessions, setSessions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState(null);
  const [newTitle, setNewTitle] = useState('');
  const [creating, setCreating] = useState(false);
  const [copiedId, setCopiedId] = useState(null);
  const [rotatingId, setRotatingId] = useState(null);

  const fetchSessions = useCallback(async () => {
    const { data, error } = await supabase
      .from('harbor_sessions')
      .select('id, title, status, guest_token, scheduled_at, started_at, ended_at, created_at')
      .order('created_at', { ascending: false })
      .limit(50);
    if (error) {
      console.error('Harbor: failed to load sessions:', error);
      setLoadError(error.message);
    } else {
      setLoadError(null);
      setSessions(data || []);
    }
    setLoading(false);
  }, []);

  useEffect(() => {
    fetchSessions();
  }, [fetchSessions]);
  useVisibilityRefresh(fetchSessions);

  const createSession = async (e) => {
    e.preventDefault();
    if (creating) return;
    setCreating(true);
    // guest_token is generated by the DB column default.
    const { data, error } = await supabase
      .from('harbor_sessions')
      .insert({ title: newTitle.trim() || 'Untitled session', created_by: profile?.id })
      .select('id, title, status, guest_token, scheduled_at, started_at, ended_at, created_at')
      .single();
    if (error) {
      console.error('Harbor: failed to create session:', error);
      setLoadError(error.message);
    } else {
      setSessions((prev) => [data, ...prev]);
      setNewTitle('');
    }
    setCreating(false);
  };

  const copyGuestLink = async (session) => {
    const link = guestJoinLink(session.guest_token);
    try {
      await navigator.clipboard.writeText(link);
      setCopiedId(session.id);
      setTimeout(() => setCopiedId((cur) => (cur === session.id ? null : cur)), 2000);
    } catch (err) {
      console.error('Harbor: clipboard write failed:', err);
      // Fallback so the link is still obtainable.
      window.prompt('Copy the guest link:', link); // eslint-disable-line no-alert
    }
  };

  // Rotate the guest link: old links 404 immediately in harbor-join; the
  // live signaling channel (named from channel_secret) and any connected
  // guests are untouched — only future joins need the new link.
  const rotateLink = async (session) => {
    if (rotatingId) return;
    // eslint-disable-next-line no-alert
    const ok = window.confirm(
      `Generate a new guest link for "${session.title}"? The old link stops working immediately. Guests already connected are not affected.`,
    );
    if (!ok) return;
    setRotatingId(session.id);
    try {
      const newToken = await rotateGuestToken(session.id);
      setSessions((prev) =>
        prev.map((s) => (s.id === session.id ? { ...s, guest_token: newToken } : s)),
      );
      setCopiedId((cur) => (cur === session.id ? null : cur)); // stale "Copied!" would lie
    } catch (err) {
      console.error('Harbor: guest link rotation failed:', err);
      setLoadError(err.message);
    } finally {
      setRotatingId(null);
    }
  };

  return (
    <div style={styles.page}>
      <div style={styles.inner}>
        {/* Suite branding + back to launcher (kept from the coming-soon page) */}
        <div style={styles.brandRow}>
          <div style={styles.brandLeft}>
            <div style={styles.tileMark}>H</div>
            <div>
              <h1 style={styles.title}>Harbor</h1>
              <p style={styles.tagline}>Podcast & remote recording</p>
            </div>
          </div>
          {onBackToLauncher && (
            <button type="button" onClick={onBackToLauncher} style={button({ variant: 'ghost', size: 'sm' })}>
              &larr; Apps
            </button>
          )}
        </div>

        {/* Create session */}
        <form onSubmit={createSession} style={styles.createRow}>
          <input
            type="text"
            value={newTitle}
            onChange={(e) => setNewTitle(e.target.value)}
            placeholder="New session title…"
            maxLength={120}
            style={styles.createInput}
          />
          <button type="submit" style={button({ disabled: creating })} disabled={creating}>
            {creating ? 'Creating…' : 'Create session'}
          </button>
        </form>

        {loadError && <div style={styles.errorBox}>Failed to load sessions: {loadError}</div>}

        {/* Sessions list */}
        <div style={styles.list}>
          {loading ? (
            <p style={styles.emptyText}>Loading sessions…</p>
          ) : sessions.length === 0 ? (
            <div style={styles.emptyCard}>
              <h2 style={sectionHeader(2)}>No sessions yet</h2>
              <p style={styles.emptyText}>
                Create a session, copy the guest link, and open the room to start a call.
              </p>
            </div>
          ) : (
            sessions.map((s) => (
              <div key={s.id} style={styles.sessionCard}>
                <div style={styles.sessionInfo}>
                  <div style={styles.sessionTitleRow}>
                    <span style={styles.sessionTitle}>{s.title}</span>
                    <span style={pill(STATUS_TONES[s.status] || 'info')}>
                      {STATUS_LABELS[s.status] || s.status}
                    </span>
                  </div>
                  <span style={styles.sessionMeta}>
                    Created {new Date(s.created_at).toLocaleDateString()}
                    {s.started_at ? ` · started ${new Date(s.started_at).toLocaleString()}` : ''}
                    {s.ended_at ? ` · ended ${new Date(s.ended_at).toLocaleString()}` : ''}
                  </span>
                </div>
                <div style={styles.sessionActions}>
                  {s.status !== 'ended' && (
                    <button
                      type="button"
                      style={button({ variant: 'ghost', size: 'sm' })}
                      onClick={() => copyGuestLink(s)}
                    >
                      {copiedId === s.id ? 'Copied!' : 'Copy guest link'}
                    </button>
                  )}
                  {s.status !== 'ended' && (
                    <button
                      type="button"
                      style={button({ variant: 'ghost', size: 'sm', disabled: rotatingId === s.id })}
                      disabled={rotatingId === s.id}
                      onClick={() => rotateLink(s)}
                    >
                      {rotatingId === s.id ? 'Rotating…' : 'New guest link'}
                    </button>
                  )}
                  <button
                    type="button"
                    style={button({ size: 'sm', disabled: s.status === 'ended' })}
                    disabled={s.status === 'ended'}
                    onClick={() => onOpenRoom?.(s.id)}
                  >
                    Open room
                  </button>
                </div>
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  );
}

const styles = {
  page: {
    minHeight: '100vh',
    background: colors.bg,
    fontFamily,
    color: colors.text,
    display: 'flex',
    justifyContent: 'center',
    padding: spacing.xxl,
    boxSizing: 'border-box',
  },
  inner: {
    width: '100%',
    maxWidth: 760,
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.xl,
  },
  brandRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    flexWrap: 'wrap',
  },
  brandLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.lg,
  },
  tileMark: {
    width: 52,
    height: 52,
    borderRadius: radii.lg,
    background: colors.info.bg,
    border: `1px solid ${colors.info.border}`,
    color: colors.info.fg,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: fontSizes.display,
    fontWeight: fontWeights.bold,
    flexShrink: 0,
  },
  title: {
    fontSize: fontSizes.displayLg,
    fontWeight: fontWeights.bold,
    margin: 0,
    letterSpacing: '-0.3px',
  },
  tagline: {
    fontSize: fontSizes.md,
    color: colors.info.fgSoft,
    margin: 0,
  },
  createRow: {
    display: 'flex',
    gap: spacing.sm,
    flexWrap: 'wrap',
  },
  createInput: {
    ...input(),
    flex: 1,
    minWidth: 200,
  },
  errorBox: {
    padding: spacing.md,
    background: colors.danger.bg,
    border: `1px solid ${colors.danger.border}`,
    borderRadius: radii.md,
    color: colors.danger.fgSoft,
    fontSize: fontSizes.md,
  },
  list: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.md,
  },
  emptyCard: {
    ...card(),
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.sm,
    alignItems: 'flex-start',
  },
  emptyText: {
    fontSize: fontSizes.md,
    color: colors.textMuted,
    margin: 0,
    lineHeight: 1.6,
  },
  sessionCard: {
    ...card(),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    flexWrap: 'wrap',
  },
  sessionInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.xs,
    minWidth: 0,
  },
  sessionTitleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.sm,
    flexWrap: 'wrap',
  },
  sessionTitle: {
    fontSize: fontSizes.lg,
    fontWeight: fontWeights.semibold,
    color: colors.text,
  },
  sessionMeta: {
    fontSize: fontSizes.sm,
    color: colors.textSubtle,
  },
  sessionActions: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.sm,
    flexWrap: 'wrap',
  },
};
